<a href="https://colab.research.google.com/github/voknerog/data_analyse/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import the numpy package under the name np (★☆☆)

In [ ]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

1.21.6


3. Create a null vector of size 10 (★☆☆)

In [ ]:
n = 10
A = np.zeros(n)

5


array([0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [ ]:
print(A.nbytes)


160


5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [ ]:
np.info(np.add)
np.info(np.array)

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
n = 10
A = np.zeros(n)
A[4] = 1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
n = 10
m = 49
A = np.arange(n, m+1)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)


In [ ]:
A = A[::-1]

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
A = np.arange(9)
A = np.reshape(A, (3, 3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a_10 = [1,2,0,0,4,0]
res_10 = np.nonzero(a_10)
res_10[0]


[0 1 4]


array([0, 1, 4])

11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
a_11 = np.identity(3)
a_11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])